databases:
  - name: urlshortener-db
    databaseName: urlshortener
    user: urlshortener

  - name: urlshortener-redis
    plan: free
    maxmemoryPolicy: allkeys-lru

services:
  - type: web
    name: url-shortener-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: urlshortener-db
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: urlshortener-redis
          property: connectionString